Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/UselessMethodDefinition:
  Enabled: false
